---
- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes
  listen: "reload systemd"
  become: yes

- name: Restart blackbox_exporter service
  systemd:
    name: blackbox_exporter
    state: restarted
  listen: "restart blackbox_exporter"
  become: yes
...
